#!/bin/bash

# Detect AppDir
APPDIR="$(dirname "$(readlink -f "$0")")"
export APPDIR


source $APPDIR/func4bash/colors.lib
source $APPDIR/func4bash/log.lib

# Set paths
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$APPDIR/usr/lib64:$LD_LIBRARY_PATH"

# Redirect WEBKIT process to right location
export WEBKIT_EXEC_PATH="$APPDIR/usr/lib/webkit2gtk-4.0"

rm /tmp/webviewer.log &> /dev/null
log.info "Log: /tmp/webviewer.log"

# WebKit and zenity Check

if [ ! -x $APPDIR/usr/bin/zenity ]; then
    log.error "Zenity not found in appimage!"
    exit 1
fi

function zenity() {
    "$APPDIR/usr/bin/zenity" "$@" &> /dev/null
}


[[ $1 == "--notify" ]] && zenity --info --text="$2" --title="Linux Web View"


if [ ! -x "$WEBKIT_EXEC_PATH/WebKitNetworkProcess" ]; then
    echo "ERROR: WebKitNetworkProcess not found!: $WEBKIT_EXEC_PATH/WebKitNetworkProcess" >&2
    zenity --error --title='ERR: WebKitNetworkProcess' --text="ERROR: WebKitNetworkProcess not found!: $WEBKIT_EXEC_PATH/WebKitNetworkProcess"
    exit 1
fi
if [ ! -x "$WEBKIT_EXEC_PATH/WebKitWebProcess" ]; then
    echo "ERROR: WebKitWebProcess found!: $WEBKIT_EXEC_PATH/WebKitWebProcess" >&2
    zenity --error --title='ERR: WEbkitWebProcess' --text="ERROR: WebKitWebProcess not found!: $WEBKIT_EXEC_PATH/WebKitWebProcess"
    exit 1
fi

# Lib Checkup
if ! [[ -d /usr/lib/webkit2gtk-4.0 ]]; then
    if [ "$USER" == "root" ]; then
        cp -r "$APPDIR/usr/lib/webkit2gtk-4.0/" /usr/lib/webkit2gtk-4.0/ &> /tmp/webviewer.log
        if ! [[ -d /usr/lib/webkit2gtk-4.0 ]]; then
            zenity --info 'ERR: webkit2gtk-4.0 installation failed.' '$(cat /tmp/webviewer.log)'  
        else
            zenity --info 'Linux Web View' 'webkit2gtk-4.0 installed successfully.'  
        fi
        exit 0
    else
        zenity --info 'LIB ERR: /usr/lib/webkit2gtk-4.0' "WebKit2GTK 4.0 is missing. Please run the program as root once to install it, after which it will be available for use."
    fi   
fi


# Detect display backend (Wayland or X11)
if [ -n "$WAYLAND_DISPLAY" ]; then
    export GDK_BACKEND=wayland
    export WEBKIT_DISABLE_COMPOSITING_MODE=1
else
    export GDK_BACKEND=x11
fi

if [[ $@ =~ "--allow-jts" ]]; then
    zenity --question --title="JS To Shell Access" --text="$1 wants to use js to shell feature. Is that okay?" || {
        log.error "JS To Shell Access Denied for $URL"
        exit 1
    }
    log.warn "Be careful, $1 has been authorized for use JS To Shell"
    [[ $UID == 0 ]] && log.sub "${RED}Root${WHITE} permission granted."
    WEBVIEWER="$APPDIR/usr/bin/webviewer-sh"
else
    WEBVIEWER="$APPDIR/usr/bin/webviewer"
fi


# Validate arguments
if ! [[ $1 =~ (http|html) ]]; then
    log.warn "Usage: ./webview.AppImage <URL or HTML file path>"
    exit 1
else
    URL="$1"
    exec "$WEBVIEWER" "$URL"  2>/tmp/webviewer.log
fi

# Default error message
log.error "Invalid input. Provide a valid URL or an existing HTML file."
exit 1
